// Generated by agent-memory. Edit defaults or override via env vars.
export {}; // mark as a module to keep scoped declarations

const MCP_ENDPOINT = process.env.GRAPHITI_MCP_URL || '{{GRAPHITI_ENDPOINT}}';
const DEFAULT_GROUP_ID = process.env.GRAPHITI_GROUP_ID || '{{GRAPHITI_GROUP}}';
const CLIENT_INFO = { name: 'agent-memory', version: '0.1.0' };
const PROTOCOL_VERSION = '2024-11-05';
const BASE_HEADERS = {
  'Content-Type': 'application/json',
  Accept: 'application/json, text/event-stream',
};

module.exports = {
  MCP_ENDPOINT,
  DEFAULT_GROUP_ID,
  CLIENT_INFO,
  PROTOCOL_VERSION,
  BASE_HEADERS,
};
