/**
 * RepoProfileService
 *
 * Generates and maintains a living markdown profile at `.lisa/data/repo-profile.md`
 * that gives every new session instant understanding of the project.
 *
 * Consumes pipeline data from Phase 1 (triage) and Phase 3 (extraction)
 * to render structured markdown with sections for overview, architecture,
 * hotspots, decisions, gotchas, and recent activity.
 *
 * Part of LISA-11: Repo Profile Generation.
 */

import path from 'node:path';
import type { IFileSystem } from '../../domain/interfaces/IFileSystem';
import type { ILogger } from '../../domain/interfaces/ILogger';
import type {
  IRepoProfileService,
  IProfileInput,
  IProfileGenerateResult,
  IProfileReadResult,
  IProfileFreshnessResult,
  IProfileGenerateOptions,
} from '../../domain/interfaces/IRepoProfileService';
import type { IFileHotspot, ITagInfo, IGitCommitData } from '../../domain/interfaces/IGitTriageService';
import type { IHeuristicFact } from '../../domain/interfaces/IGitExtractor';

/** Relative path from project root to the profile file. */
const PROFILE_RELATIVE_PATH = path.join('.lisa', 'data', 'repo-profile.md');

/** Total number of content sections in the profile template. */
const TOTAL_SECTIONS = 8;

/** Default generation options. */
const DEFAULT_OPTIONS: Required<IProfileGenerateOptions> = {
  maxHotspots: 10,
  maxFactsPerSection: 10,
  maxRecentCommits: 10,
};

/** Freshness thresholds in hours. */
const FRESH_THRESHOLD_HOURS = 24;
const STALE_THRESHOLD_HOURS = 168; // 7 days

/**
 * Resolve the absolute path to the profile file.
 */
function getProfilePath(projectRoot: string): string {
  return path.join(projectRoot, PROFILE_RELATIVE_PATH);
}

/**
 * Calculate freshness state from file modification timestamp.
 * Pure function for testability.
 */
export function calculateFreshness(
  mtimeMs: number | null,
  now: number = Date.now()
): IProfileFreshnessResult {
  if (mtimeMs === null) {
    return {
      freshness: 'missing',
      lastUpdated: null,
      ageHours: null,
      note: 'No profile found. Run `lisa onboard` to generate.',
    };
  }

  const ageHours = (now - mtimeMs) / (1000 * 60 * 60);
  const lastUpdated = new Date(mtimeMs);

  if (ageHours <= FRESH_THRESHOLD_HOURS) {
    return {
      freshness: 'fresh',
      lastUpdated,
      ageHours: Math.round(ageHours * 10) / 10,
      note: 'Profile is up to date.',
    };
  }

  if (ageHours <= STALE_THRESHOLD_HOURS) {
    const days = Math.round(ageHours / 24);
    return {
      freshness: 'stale',
      lastUpdated,
      ageHours: Math.round(ageHours * 10) / 10,
      note: `Profile may be stale (${days} day${days !== 1 ? 's' : ''} old).`,
    };
  }

  const days = Math.round(ageHours / 24);
  return {
    freshness: 'expired',
    lastUpdated,
    ageHours: Math.round(ageHours * 10) / 10,
    note: `Profile is outdated (${days} days old). Run \`lisa onboard --refresh\`.`,
  };
}

/**
 * Render the full profile markdown from pipeline data.
 * Pure function for testability.
 */
export function renderMarkdown(
  input: IProfileInput,
  options: Required<IProfileGenerateOptions>
): { markdown: string; sectionsPopulated: number } {
  const { projectName, triage, extraction, codebaseSummary, recentCommits, generatedAt } = input;
  const dateStr = generatedAt.toISOString().split('T')[0];

  const sections: string[] = [];
  let sectionsPopulated = 0;

  // Header
  sections.push(`# Repo Profile: ${projectName}`);
  sections.push(`> Generated by \`lisa onboard\` on ${dateStr}. Last updated: ${dateStr}.`);
  sections.push('');

  // 1. Project Overview
  sections.push('## Project Overview');
  if (codebaseSummary) {
    sections.push('');
    sections.push(codebaseSummary);
    sectionsPopulated++;
  } else {
    sections.push('');
    sections.push('*No codebase summary available. Run `lisa onboard` with init-review to generate.*');
  }
  sections.push('');

  // 2. Architecture Evolution
  sections.push('## Architecture Evolution');
  const archContent = renderArchitectureEvolution(triage?.tags, extractFactsByType(extraction?.facts, 'decision'));
  if (archContent) {
    sections.push('');
    sections.push(archContent);
    sectionsPopulated++;
  } else {
    sections.push('');
    sections.push('*No version tags or architectural decisions captured yet.*');
  }
  sections.push('');

  // 3. Hotspots
  sections.push('## Hotspots');
  const hotspotsContent = renderHotspots(triage?.hotspots, options.maxHotspots);
  if (hotspotsContent) {
    sections.push('');
    sections.push(hotspotsContent);
    sectionsPopulated++;
  } else {
    sections.push('');
    sections.push('*No hotspot data available.*');
  }
  sections.push('');

  // 4. Feature Waves
  sections.push('## Feature Waves');
  const wavesContent = renderFeatureWaves(triage?.tags);
  if (wavesContent) {
    sections.push('');
    sections.push(wavesContent);
    sectionsPopulated++;
  } else {
    sections.push('');
    sections.push('*No version tag data available.*');
  }
  sections.push('');

  // 5. Key Decisions
  sections.push('## Key Decisions');
  const decisions = extractFactsByType(extraction?.facts, 'decision');
  const decisionsContent = renderFactList(decisions, options.maxFactsPerSection);
  if (decisionsContent) {
    sections.push('');
    sections.push(decisionsContent);
    sectionsPopulated++;
  } else {
    sections.push('');
    sections.push('*No decisions captured yet.*');
  }
  sections.push('');

  // 6. Known Gotchas
  sections.push('## Known Gotchas');
  const gotchas = extractFactsByType(extraction?.facts, 'gotcha');
  const gotchasContent = renderFactList(gotchas, options.maxFactsPerSection);
  if (gotchasContent) {
    sections.push('');
    sections.push(gotchasContent);
    sectionsPopulated++;
  } else {
    sections.push('');
    sections.push('*No gotchas captured yet.*');
  }
  sections.push('');

  // 7. Active Concerns
  sections.push('## Active Concerns');
  const conventions = extractFactsByType(extraction?.facts, 'convention');
  const concernsContent = renderFactList(conventions, options.maxFactsPerSection);
  if (concernsContent) {
    sections.push('');
    sections.push(concernsContent);
    sectionsPopulated++;
  } else {
    sections.push('');
    sections.push('*No conventions or active concerns captured yet.*');
  }
  sections.push('');

  // 8. Recent Activity
  sections.push('## Recent Activity');
  const activityContent = renderRecentActivity(recentCommits, options.maxRecentCommits);
  if (activityContent) {
    sections.push('');
    sections.push(activityContent);
    sectionsPopulated++;
  } else {
    sections.push('');
    sections.push('*No recent commits found.*');
  }
  sections.push('');

  return {
    markdown: sections.join('\n'),
    sectionsPopulated,
  };
}

/**
 * Extract facts of a specific type from extraction results.
 */
function extractFactsByType(
  facts: readonly IHeuristicFact[] | undefined,
  type: 'decision' | 'gotcha' | 'convention'
): readonly IHeuristicFact[] {
  if (!facts) return [];
  return facts.filter(f => f.type === type);
}

/**
 * Render the Architecture Evolution section.
 * Combines version tags and decision facts.
 */
function renderArchitectureEvolution(
  tags: readonly ITagInfo[] | undefined,
  decisions: readonly IHeuristicFact[]
): string | null {
  const parts: string[] = [];

  // Version timeline
  const versionTags = tags?.filter(t => t.isVersionTag) ?? [];
  if (versionTags.length > 0) {
    parts.push('### Version Timeline');
    parts.push('');
    for (const tag of versionTags.slice(0, 20)) {
      parts.push(`- \`${tag.name}\``);
    }
    if (versionTags.length > 20) {
      parts.push(`- ... and ${versionTags.length - 20} more`);
    }
  }

  // Architectural decisions
  if (decisions.length > 0) {
    if (parts.length > 0) parts.push('');
    parts.push('### Architectural Decisions');
    parts.push('');
    for (const fact of decisions.slice(0, 5)) {
      const ref = formatFactReference(fact);
      parts.push(`- ${fact.text}${ref}`);
    }
  }

  return parts.length > 0 ? parts.join('\n') : null;
}

/**
 * Render the Hotspots section as a markdown table.
 */
function renderHotspots(
  hotspots: readonly IFileHotspot[] | undefined,
  max: number
): string | null {
  if (!hotspots || hotspots.length === 0) return null;

  const limited = hotspots.slice(0, max);
  const lines: string[] = [];

  lines.push('| File | Commits | Lines Changed |');
  lines.push('|------|---------|---------------|');
  for (const h of limited) {
    lines.push(`| \`${h.path}\` | ${h.commitCount} | ${h.totalLinesChanged.toLocaleString()} |`);
  }

  if (hotspots.length > max) {
    lines.push('');
    lines.push(`*... and ${hotspots.length - max} more files.*`);
  }

  return lines.join('\n');
}

/**
 * Render the Feature Waves section.
 * Groups version tags by major version.
 */
function renderFeatureWaves(
  tags: readonly ITagInfo[] | undefined
): string | null {
  const versionTags = tags?.filter(t => t.isVersionTag) ?? [];
  if (versionTags.length === 0) return null;

  // Group by major version (e.g., v1.x, v2.x)
  const groups = new Map<string, ITagInfo[]>();
  for (const tag of versionTags) {
    const match = tag.name.match(/^v?(\d+)/);
    const major = match ? `v${match[1]}.x` : 'other';
    const group = groups.get(major) ?? [];
    group.push(tag);
    groups.set(major, group);
  }

  const lines: string[] = [];
  for (const [major, groupTags] of groups) {
    lines.push(`**${major}**: ${groupTags.map(t => `\`${t.name}\``).join(', ')}`);
  }

  return lines.join('\n\n');
}

/**
 * Render a list of facts as bullet points with references.
 */
function renderFactList(
  facts: readonly IHeuristicFact[],
  max: number
): string | null {
  if (facts.length === 0) return null;

  const limited = facts.slice(0, max);
  const lines = limited.map(fact => {
    const ref = formatFactReference(fact);
    return `- ${fact.text}${ref}`;
  });

  if (facts.length > max) {
    lines.push(`- *... and ${facts.length - max} more.*`);
  }

  return lines.join('\n');
}

/**
 * Format a fact's PR/issue reference as a parenthetical.
 */
function formatFactReference(fact: IHeuristicFact): string {
  const refs: string[] = [];
  if (fact.prNumber !== undefined) refs.push(`PR #${fact.prNumber}`);
  if (fact.issueNumber !== undefined) refs.push(`Issue #${fact.issueNumber}`);
  return refs.length > 0 ? ` *(${refs.join(', ')})* ` : '';
}

/**
 * Render the Recent Activity section.
 */
function renderRecentActivity(
  commits: readonly IGitCommitData[] | undefined,
  max: number
): string | null {
  if (!commits || commits.length === 0) return null;

  const limited = commits.slice(0, max);
  const lines = limited.map(c => `- \`${c.shortSha}\` ${c.subject}`);

  if (commits.length > max) {
    lines.push(`- *... and ${commits.length - max} more.*`);
  }

  return lines.join('\n');
}

/**
 * Create a Repo Profile service.
 *
 * @param fs - File system abstraction for reading/writing the profile
 * @param logger - Optional logger
 * @returns A Repo Profile service
 */
export function createRepoProfileService(
  fs: IFileSystem,
  logger?: ILogger
): IRepoProfileService {
  return {
    async generate(
      input: IProfileInput,
      options: IProfileGenerateOptions = {}
    ): Promise<IProfileGenerateResult> {
      const merged: Required<IProfileGenerateOptions> = {
        ...DEFAULT_OPTIONS,
        ...options,
      };

      const filePath = getProfilePath(input.projectRoot);

      logger?.debug('Generating repo profile', {
        projectName: input.projectName,
        filePath,
        hasTriage: !!input.triage,
        hasExtraction: !!input.extraction,
        hasSummary: !!input.codebaseSummary,
        recentCommitCount: input.recentCommits?.length ?? 0,
      });

      const { markdown, sectionsPopulated } = renderMarkdown(input, merged);

      await fs.writeFile(filePath, markdown);

      logger?.info('Repo profile generated', {
        filePath,
        sectionsPopulated,
        totalSections: TOTAL_SECTIONS,
      });

      return {
        markdown,
        filePath,
        sectionsPopulated,
        totalSections: TOTAL_SECTIONS,
      };
    },

    async read(projectRoot: string): Promise<IProfileReadResult> {
      const filePath = getProfilePath(projectRoot);
      const stat = await fs.stat(filePath);
      const freshness = calculateFreshness(stat?.mtimeMs ?? null);

      let markdown: string | null = null;
      if (stat !== null) {
        try {
          markdown = await fs.readFile(filePath);
        } catch (error) {
          logger?.warn('Failed to read repo profile', {
            filePath,
            error: (error as Error).message,
          });
        }
      }

      return { markdown, freshness, filePath };
    },

    async checkFreshness(projectRoot: string): Promise<IProfileFreshnessResult> {
      const filePath = getProfilePath(projectRoot);
      const stat = await fs.stat(filePath);
      return calculateFreshness(stat?.mtimeMs ?? null);
    },
  };
}
